feature/checkCourseName
devonfw-tutorials/tutorials pull request #113
Opened 2021-05-21 10:18 UTC by denise-khuu

# What will the user learn in your tutorial?

# What should the user already know when starting the tutorial?

2021-05-27 07:28 UTC, GuentherJulian requested changes

2021-05-27 07:28 UTC, GuentherJulian commented on .github/workflows/checkCourseName.yml
> +          path: playbooks
I think the path and the repository parameter are not needed here

2021-05-27 07:28 UTC, GuentherJulian commented on .github/workflows/checkCourseName.yml
> +            message="${message} You just tried to name a course that is already a playbook.\n Please change the name. \n"
I think you have to remove the line breaks in the message. I also wanted to add some in the workflow for auto reviewing. But that resulted in the text not being displayed after the first line break.

2021-06-10 05:28 UTC, SchettlerKoehler approved these changes

2021-06-25 08:29 UTC, merged