reviewUpdate_restclientchangedtitle
devonfw-tutorials/tutorials pull request #154
Opened 2021-06-25 10:17 UTC by dixyushi

# What will the user learn in your tutorial?

# What should the user already know when starting the tutorial?

2021-06-29 05:39 UTC, ssarmokadam submitted a review, later dismissed

2021-07-05 05:18 UTC, SchettlerKoehler requested changes

2021-07-05 05:18 UTC, SchettlerKoehler commented on devon4j-http-rest-client/index.asciidoc
> +nextKatacodaStep("Start the CXF CLient Server", [{ "file": "files/startServer.md" }])
Please do not use nextKatacodaStep. Everything you do with nextKatacodaStep is not tested. Everything you have done in this step can be done without nextKatacodaStep!

2021-07-08 05:12 UTC, SchettlerKoehler approved these changes

2021-07-08 05:12 UTC, merged