feature/tutorial-compiler
devonfw-tutorials/tutorials pull request #27
Opened 2021-02-24 16:29 UTC by denise-khuu

2021-03-03 09:34 UTC, GuentherJulian requested changes

2021-03-03 09:34 UTC, GuentherJulian commented on tutorial-compiler/index.asciidoc
> + * github-account
GitHub is a name, so better write it as GitHub account

2021-03-03 09:34 UTC, GuentherJulian commented on tutorial-compiler/index.asciidoc
> +Fork the repository by clicking on the fork-button.
Here we can mention that this will create a copy of the repo in the users GitHub account

2021-03-03 09:34 UTC, GuentherJulian commented on tutorial-compiler/index.asciidoc
> +Go to your repositories, click on 'tutorial-compiler' and copy the repository Url as shown in image below.
Sometimes you use Url and sometimes URL. I would suggest to write URL everywhere, because it is an abbreviation.

2021-03-03 09:34 UTC, GuentherJulian commented on tutorial-compiler/index.asciidoc
> +Afterwards we will show you, how to write your own tutorials using an asciidoc.
I think we should not mention here that tutorials are written in asciidoc files. We should say it later when we create the file. We should also link the development part of the wiki somewhere.

2021-03-04 10:31 UTC, MarcelDiessner commented
You should now be able to use multiple functions per step

2021-03-08 12:17 UTC, GuentherJulian commented
I am not sure why, but at the moment there is something wrong with step 4 and 5. https://github.com/devonfw-tutorials/katacoda-scenarios-dev/tree/main/27_tutorial-compiler_tutorial-compiler
There is no step 6 and in the index.json there is step 4 twice. Therefore it is displayed incorrectly in Katacoda.
Can you check why? Maybe this is related to Marcel's last change to show multiple steps in one.

2021-03-08 14:21 UTC, MarcelDiessner commented
> I am not sure why, but at the moment there is something wrong with step 4 and 5. https://github.com/devonfw-tutorials/katacoda-scenarios-dev/tree/main/27_tutorial-compiler_tutorial-compiler
> There is no step 6 and in the index.json there is step 4 twice. Therefore it is displayed incorrectly in Katacoda.
> Can you check why? Maybe this is related to Marcel's last change to show multiple steps in one.

Yes it was due to a missing refactoring by me when using npmInstall. When the fixing pull-request is merged it should work.

2021-03-09 08:18 UTC, GuentherJulian requested changes

2021-03-09 08:18 UTC, GuentherJulian commented on tutorial-compiler/index.asciidoc
> +
We should also add a step that shows how to run the tutorial with the tutorial-compiler (either with executeFile or nextKatacodaStep)

2021-03-10 17:10 UTC, GuentherJulian approved these changes

2021-03-11 11:59 UTC, merged