first commit for cobigen setup
devonfw-tutorials/tutorials pull request #66
Opened 2021-03-16 19:27 UTC by dixyushi

2021-03-20 09:36 UTC, GuentherJulian commented
The parser expects at least one step. Therefore the pipeline fails at the moment

2021-03-22 09:12 UTC, SchettlerKoehler requested changes

2021-03-22 09:12 UTC, SchettlerKoehler commented on cobigen-setup/index.asciidoc
> +== Install CobiGen and create Java Project
This is a syntax error. See https://github.com/devonfw-tutorials/tutorials/wiki/Development

2021-03-22 09:12 UTC, SchettlerKoehler commented on cobigen-setup/index.asciidoc
> +====
This is a syntax error. See https://github.com/devonfw-tutorials/tutorials/wiki/Development

2021-03-26 07:34 UTC, closed without merging

2021-03-26 07:35 UTC, dixyushi commented
I have created new drafted pull request. This branch is deleted because of issue which were created earlier. Hence working on one branch and closing this pull request