issue#33: devon4j architecture tutorial
devonfw-tutorials/tutorials pull request #70
Opened 2021-03-23 06:30 UTC by ssarmokadam

2021-03-30 10:07 UTC, SchettlerKoehler requested changes

2021-03-30 10:07 UTC, SchettlerKoehler commented on devon4j-architecture/principles.md
> +As an architect you should be prepared for the future by reading the [TechnoVision](https://www.capgemini.com/de-de/wp-content/uploads/sites/5/2020/07/TechnoVision-2020-Report.pdf).
@maybeec do you think we should have this link here?

2021-03-30 10:07 UTC, SchettlerKoehler commented on devon4j-architecture/index.asciidoc
> +createDevon4jProject("sampleapp")
I think you are creating the project to show the user the architecture, but this is missing. You should point the user to the parts of the project where the things you are mentioned are visible.

2021-04-01 08:33 UTC, SchettlerKoehler requested changes

2021-04-15 06:45 UTC, ssarmokadam commented on devon4j-architecture/index.asciidoc
> +installDevonfwIde(["java","mvn","vscode"])
Done

2021-04-15 06:45 UTC, ssarmokadam commented on devon4j-architecture/index.asciidoc
> +* Using command line as shown [here](https://devonfw.com/website/pages/docs/devon4j.asciidoc_tutorials.html#tutorial-newapp.asciidoc_from-command-line)
I have rearranged text to make it clear

2021-04-15 06:45 UTC, ssarmokadam commented on devon4j-architecture/index.asciidoc
> +nextKatacodaStep("devon4j application architecture", [{ "image": "images/devon4j_proj_structure1.jpg" }])
Done

2021-04-15 06:46 UTC, ssarmokadam commented on devon4j-architecture/index.asciidoc
> +nextKatacodaStep("devon4j application architecture", [{ "image": "images/devon4j_proj_structure1.jpg" }])
I have added links of wiki as we do not want to repeat it

2021-04-21 09:49 UTC, MarcelDiessner commented
You can now add a conclusion text which is shown at the end of the katacoda tutorial and the wiki. See https://github.com/devonfw-tutorials/tutorials/wiki/Development for further informations

2021-04-21 12:07 UTC, MarcelDiessner commented
You can now add a subtitle with the == syntax. See https://github.com/devonfw-tutorials/tutorials/wiki/Development

2021-04-23 06:57 UTC, sujith-mn approved these changes

2021-04-23 06:57 UTC, merged