Angular tutorial for lazy loading using devon4ng
devonfw-tutorials/tutorials pull request #93
Opened 2021-04-29 15:53 UTC by suprishi

# What will the user learn in your tutorial?

# What should the user already know when starting the tutorial?

2021-05-17 07:10 UTC, SchettlerKoehler requested changes

2021-05-17 07:10 UTC, SchettlerKoehler commented on devon4ng-lazy-loading/index.asciidoc
> +createDevon4ngProject("level-app", "", ["--style=scss", "--routing=true", "--strict=false"])
Maybe this could help: https://github.com/devonfw-tutorials/tutorial-compiler/blob/main/documentation/Functions.md#addsetupscript

2021-05-20 04:11 UTC, suprishi commented on devon4ng-lazy-loading/index.asciidoc
> +* devonfw-ide installed
I removed the pre-requisite.

2021-05-20 04:11 UTC, suprishi commented on devon4ng-lazy-loading/index.asciidoc
> +restoreDevonfwIde(["java","mvn", "npm", "ng"])
Added `vscode`

2021-05-20 04:19 UTC, suprishi commented on devon4ng-lazy-loading/index.asciidoc
> +createDevon4ngProject("level-app", "", ["--style=scss", "--routing=true", "--strict=false"])
Although the git error is not blocking the flow of the tutorial (the user can still proceed by executing subsequent commands in the tutorial), I tried running the `git config` commands using the `addSetupScript` function. But it does not seem to work! The integrated terminal in the katacoda (dev environment) halts at the message `Executing step: Run setup.sh`

2021-06-10 04:54 UTC, SchettlerKoehler commented on devon4ng-lazy-loading/index.asciidoc
> +createDevon4ngProject("level-app", "", ["--style=scss", "--routing=true", "--strict=false"])
You should add an explicit step for the user to do it so there are no confusing errors.

2021-07-05 07:44 UTC, SchettlerKoehler commented
What is the state of this PR?

2021-07-05 15:03 UTC, suprishi commented
> What is the state of this PR?

Waiting for the corresponding story to get into active sprint so I can continue to work on this.

2021-08-02 05:33 UTC, SchettlerKoehler commented on devon4ng-lazy-loading/index.asciidoc
> +nextKatacodaStep("Introduction", [{ "file": "files/intro.txt" }, { "image": "images/levels-app.png" }])
Please do not use nextKatacodaStep

2021-08-02 05:33 UTC, SchettlerKoehler commented on devon4ng-lazy-loading/index.asciidoc
> +nextKatacodaStep("Eager loading", [{ "file": "files/eager-loading.txt" }, { "image": "images/compile-eager.png" }, { "image": "images/second-lvl-right-eager.png" }])
Please do not use nextKatacodaStep

2021-08-17 06:29 UTC, ssarmokadam approved these changes

2021-08-18 05:24 UTC, merged